### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by hammi85** [cmusphinx/node-pocketsphinx#13]
Hi,

when I try to install pocketsphinx with npm I get the following error on my raspberry:

gyp verb download contents checksum {"node-v4.2.1-headers.tar.gz":"b242fd0fa83748d95cc3e68d14579b629960b0436d65da9d86907eef27b96fc1"}
gyp verb validating download checksum for node-v4.2.1-headers.tar.gz (b242fd0fa83748d95cc3e68d14579b629960b0436d65da9d86907eef27b96fc1 == b242fd0fa83748d95cc3e68d14579b629960b0436d65da9d86907eef27b96fc1)
gyp verb get node dir target node version installed: 4.2.1
gyp verb build dir attempting to create "build" dir: /usr/local/src/node/node_modules/pocketsphinx/build
gyp verb build dir "build" dir needed to be created? /usr/local/src/node/node_modules/pocketsphinx/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/local/src/node/node_modules/pocketsphinx/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/local/src/node/node_modules/pocketsphinx/config.gypi
gyp verb common.gypi checking for gypi file: /usr/local/src/node/node_modules/pocketsphinx/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/node/node_modules/pocketsphinx/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/src/node/node_modules/pocketsphinx/.node-gyp/4.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/local/src/node/node_modules/pocketsphinx/.node-gyp/4.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/src/node/node_modules/pocketsphinx',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /usr/local/src/node/node_modules/pocketsphinx/.node-gyp/4.2.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/usr/local/src/node/node_modules/pocketsphinx/build'
make: *** No rule to make target '/swig/pocketsphinx.i', needed by 'ps.cpp'.  Stop.
make: Leaving directory '/usr/local/src/node/node_modules/pocketsphinx/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-v" "rebuild"
gyp ERR! cwd /usr/local/src/node/node_modules/pocketsphinx
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.1.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.2 install: `node-gyp -v rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pocketsphinx@5.0.2 install script 'node-gyp -v rebuild'.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp -v rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/src/node/npm-debug.log

Do you maybe have any idea how to fix it, Pocketsphinx on my raspberry is running fine so far I just can't install the node part.

Thanks!

**Comment by nshmyrev** [comment]
You need to install latest pocketsphinx from github and remove older installation.

Also make sure you have pkg-config.

This is covered in README.

**Comment by nshmyrev** [comment]
I added explicit check in updated version

**Comment by hammi85** [comment]
okay and thanks for the fast response!
