### ISSUE TITLE
Can I read directly from the microphone in node-pocketsphinx?

### ISSUE THREAD

**Issue by seandoyle** [cmusphinx/node-pocketsphinx#2]
Hi -

I'd like the ability to read from the local microphone instead of from the web page.  Is there a way to specify the local microphone similar to the "-inmic yes" option in pocketsphinx?

Thanks. 

Sean

**Comment by mbait** [comment]
No, you should read the microphone data yourself and feed it to the library by calling `.write()` or `.writeSync()`.
