### ISSUE TITLE
Generate Time Stamps in Logs

### ISSUE THREAD

**Issue by ashishbajaj99** [cmusphinx/node-pocketsphinx#20]
Currently I am using pocketsphinx in kws mode connected up to my microphone. Its working well, but randomly stops working after many hours of use. My microphone data is still streaming and working, but pocketsphinx seems to have stopped. Is it possible to get time stamps in the logs? Also what are all the logging options available to me? 

An example would be awesome...here is what I have been using:
```
var config = new ps.Decoder.defaultConfig();
config.setString("-hmm", modeldir + "en-us");
config.setString("-dict", ashiyaModelDir + "4932.dic");
config.setString("-kws", "keyphrase.txt");
config.setString("-logfn", "pocketsphinx-logs.txt");
var decoder = new ps.Decoder(config);
```

**Comment by nshmyrev** [comment]
It is not possible, you can use http://unix.stackexchange.com/questions/26728/prepending-a-timestamp-to-each-line-of-output-from-a-command
