### ISSUE TITLE
npm install fails on Raspberry Pi

### ISSUE THREAD

**Issue by mikehenrty** [cmusphinx/node-pocketsphinx#22]
SphinxBase.target.mk:118: recipe for target 'Release/obj.target/SphinxBase/wrap_sb.o' failed
build error log: http://pastebin.com/Hv3L8TmL
node: 5.7.0
npm: 3.6.0
gcc: 4.9.2 (Raspbian 4.9.2-10)
`pkg-config --modversion pocketsphinx` = 5prealpha
both sphinxbase and pocketsphinx compiled from source
sphinxbase commit: becdd6d41dc2095d8313eff1343d8ab26cdec427
pocketsphinx commit: f15834917294966c604cd709aa1c0255533c677b
`pocketsphinx_continuous` works fine (albeit slow with the default dictionary)

**Comment by nshmyrev** [comment]
What is your swig version? Please sure you are using latest one (3.0.7).

**Comment by mikehenrty** [comment]
Wow, you are fast.

SWIG Version 3.0.2. I'll try updating it and get back to you.

**Comment by mikehenrty** [comment]
Updated to Swig 3.0.8 and everything works great now. Thanks!

**Comment by nshmyrev** [comment]
Thank you, let me know if you have further questions
