### ISSUE TITLE
npm install fails on raspberry pi 2

### ISSUE THREAD

**Issue by jmadan** [cmusphinx/node-pocketsphinx#25]
Versions installed 
cmake version 3.5.2
SWIG Version 3.0.7
$PKG_CONFIG_PATH = /usr/local/lib/pkgconfig
pkg-config --modversion pocketsphinx  = 5prealpha

When I run >npm install pocketsphinx I get the following error

$ npm install pocketsphinx
|
> pocketsphinx@5.0.7 install /home/pi/node_modules/pocketsphinx
> cmake-js compile

info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info CMD CONFIGURE
info RUN cmake "/home/pi/node_modules/pocketsphinx" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/node_modules/pocketsphinx/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v4.3.2/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="4.3.2" -DNODE_ARCH="arm" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
CMake Error at /usr/local/share/cmake-3.5/Modules/FindSWIG.cmake:50 (message):
  Command "/home/pi/node_modules/.bin/swig -swiglib" failed with output:

   Usage:
      /usr/local/bin/node ../../.bin/swig compile [files] [options]
      /usr/local/bin/node ../../.bin/swig run [files] [options]
      /usr/local/bin/node ../../.bin/swig render [files] [options]

  Options:

    -v, --version  Show the Swig version number.
    -o, --output   Output location.                                                                     [default: "stdout"]
    -h, --help     Show this help screen.
    -j, --json     Variable context as a JSON file.
    -c, --context  Variable context as a CommonJS-style file. Used only if option `j` is not provided.
    -m, --minify   Minify compiled functions with uglify-js
    --filters      Custom filters as a CommonJS-style file
    --tags         Custom tags as a CommonJS-style file
    --options      Customize Swig's Options from a CommonJS-style file
    --wrap-start   Template wrapper beginning for "compile".                                            [default: "var tpl = "]
    --wrap-end     Template wrapper end for "compile".                                                  [default: ";"]
    --method-name  Method name to set template to and run from.                                         [default: "tpl"]

  [Error]

Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)

CMake Error at /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SWIG (missing: SWIG_DIR) (Required is at least version
  "3.0.7")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.5/Modules/FindSWIG.cmake:75 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/node_modules/pocketsphinx/build/CMakeFiles/CMakeOutput.log".
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "/home/pi/node_modules/pocketsphinx/build"
info CMD CONFIGURE
info RUN cmake "/home/pi/node_modules/pocketsphinx" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/node_modules/pocketsphinx/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v4.3.2/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="4.3.2" -DNODE_ARCH="arm" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
CMake Error at /usr/local/share/cmake-3.5/Modules/FindSWIG.cmake:50 (message):
  Command "/home/pi/node_modules/.bin/swig -swiglib" failed with output:

   Usage:
      /usr/local/bin/node ../../.bin/swig compile [files] [options]
      /usr/local/bin/node ../../.bin/swig run [files] [options]
      /usr/local/bin/node ../../.bin/swig render [files] [options]

  Options:

    -v, --version  Show the Swig version number.
    -o, --output   Output location.                                                                     [default: "stdout"]
    -h, --help     Show this help screen.
    -j, --json     Variable context as a JSON file.
    -c, --context  Variable context as a CommonJS-style file. Used only if option `j` is not provided.
    -m, --minify   Minify compiled functions with uglify-js
    --filters      Custom filters as a CommonJS-style file
    --tags         Custom tags as a CommonJS-style file
    --options      Customize Swig's Options from a CommonJS-style file
    --wrap-start   Template wrapper beginning for "compile".                                            [default: "var tpl = "]
    --wrap-end     Template wrapper end for "compile".                                                  [default: ";"]
    --method-name  Method name to set template to and run from.                                         [default: "tpl"]

  [Error]

Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)

CMake Error at /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find SWIG (missing: SWIG_DIR) (Required is at least version
  "3.0.7")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.5/Modules/FindSWIG.cmake:75 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/node_modules/pocketsphinx/build/CMakeFiles/CMakeOutput.log".
ERR! OMG Process terminated: 1
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by nshmyrev** [comment]
You did not install swig properly, it has no swiglib. Make sure your swig properly installed from source.
