### ISSUE TITLE
Error with npm install on Intel Edison

### ISSUE THREAD

**Issue by ShwethaSwaminathan** [cmusphinx/node-pocketsphinx#28]
I'm trying to get this on the Intel Edison. However, when I type npm install pocketsphinx it gives me the following errors:

ERR! OMG Process terminated: 1

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script.
npm ERR! This is most likely a problem with the pocket sphinx package
npm ERR! not with nam itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls pocket sphinx
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.17-poky-edison+
npm ERR! command "node" "/usr/bin/npm" "install" "pocket sphinx
npm ERR! cwd /home/root/Sphinx
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by nshmyrev** [comment]
The real error is few lines above the first line you posted. You just need to read it.

**Comment by ShwethaSwaminathan** [comment]
Alright. Thank you!
