### ISSUE TITLE
New version of pocketsphinx generates error for demo example

### ISSUE THREAD

**Issue by seandoyle** [cmusphinx/node-pocketsphinx#3]
Hi -

When I check out the latest sphinxbase/pocketsphinx/node-pocketsphinx libraries and try to run the demo example on an Ubuntu laptop I get the following warning:
WARN: "pocketsphinx.c", line 1045: Data size is too large, word timings might be wrong, process audio in smaller chunks
I see in the pocketsphinx project that this was added a few days ago. When I run pocketsphinx_continuous from the command line everything works so I'm hoping that I just need to be explicit (somewhere) about setting the data size. 

Thanks

**Comment by nshmyrev** [comment]
You need to reduce the size of audio buffer you pass to pocketsphinx. This size is set in javascript in recorder setup I believe.

**Comment by nshmyrev** [comment]
Tracked at https://sourceforge.net/p/cmusphinx/bugs/427/
