### ISSUE TITLE
npm installation failing on Raspberry Pi 3.

### ISSUE THREAD

**Issue by sanket-mindstix** [cmusphinx/node-pocketsphinx#31]
I am trying to install npm install on raspberry pi model 3 version but it is failing at my end.

Following are the specifications,
node- v4.4.5
npm- 2.15.5
SWIG Version 3.0.10.

Following error message received 
> pocketsphinx@5.0.7 install /home/pi/node-pocket/node_modules/pocketsphinx
> cmake-js compile

info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info DIST Downloading distribution files.
ERR! OMG EACCES: permission denied, mkdir '/root/.cmake-js/node-arm/v4.4.5'
ERR! OMG EACCES: permission denied, mkdir '/root/.cmake-js/node-arm/v4.4.5'
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-pocket/npm-debug.log

**Comment by nshmyrev** [comment]
Install software as a user, not as root.

**Comment by sanket-mindstix** [comment]
Still getting error when I try to install it using normal user,

Following error message received,
> pocketsphinx@5.0.7 install /home/pi/node-pocket/node_modules/pocketsphinx
> cmake-js compile

info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info CMD CONFIGURE
info RUN cmake "/home/pi/node-pocket/node_modules/pocketsphinx" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="3.2.1" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/node-pocket/node_modules/pocketsphinx/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v4.4.5/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="4.4.5" -DNODE_ARCH="arm" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 3.0.2


-- Configuring incomplete, errors occurred!
See also "/home/pi/node-pocket/node_modules/pocketsphinx/build/CMakeFiles/CMakeOutput.log".
info REP Build has been failed, trying to do a full rebuild.
info CMD CLEAN
info RUN cmake -E remove_directory "/home/pi/node-pocket/node_modules/pocketsphinx/build"
info CMD CONFIGURE
info RUN cmake "/home/pi/node-pocket/node_modules/pocketsphinx" --no-warn-unused-cli -G"Unix Makefiles" -DCMAKE_JS_VERSION="3.2.1" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/pi/node-pocket/node_modules/pocketsphinx/build/Release" -DCMAKE_JS_INC="/home/pi/.cmake-js/node-arm/v4.4.5/include/node" -DNODE_RUNTIME="node" -DNODE_RUNTIMEVERSION="4.4.5" -DNODE_ARCH="arm" -DCMAKE_CXX_FLAGS="-std=c++11"
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 3.0.2


-- Configuring incomplete, errors occurred!
See also "/home/pi/node-pocket/node_modules/pocketsphinx/build/CMakeFiles/CMakeOutput.log".
ERR! OMG Process terminated: 1
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node-pocket/npm-debug.log

**Comment by nshmyrev** [comment]
CMake 3.1 or higher is required. You are running version 3.0.2

**Comment by berzhok** [comment]
i try to install on debian

-- Configuring incomplete, errors occurred!
ERR! OMG Process terminated: 1
npm ERR! Linux 2.6.32-042stab116.2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-18T12_28_41_619Z-debug.log

**Comment by nshmyrev** [comment]
@berzhok this issue is already closed, you have to report a new one. You also need to include debug log like the message suggests.
