### ISSUE TITLE
Error: Module version mismatch. Expected 49, got 48.

### ISSUE THREAD

**Issue by causztic** [cmusphinx/node-pocketsphinx#32]
Hello,

I've installed sphinxbase and pocketphinx from the github repository as per the README on my OSX El Capitan.

I managed to compile node-pocketsphinx properly with cmake-js, and tried the commands on the Readme to test that pocketsphinx is indeed working. However, i'm getting the Module version mismatch error whenever I try to call the module on `npm start`.

My node version is `v6.2.2` and npm is `3.9.5`.

I tried reinstalling the entire `node_modules` by deleting it and reinstalling, and even re-downloaded node and npm, but to no avail.

Any ideas?

**Comment by nshmyrev** [comment]
You need to provide exact and complete output of the problematic command.

**Comment by causztic** [comment]
`
> electron .

App threw an error during load
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yaojie/Work/eve/node_modules/pocketsphinx/index.js:1:99)
`

**Comment by nshmyrev** [comment]
It seems that you have several node installations in your system, electron runs under some development version of node (49), you build for version 48 (https://nodejs.org/en/download/releases/). You need to figure out why electron runs under newer version and downgrade it. Maybe you need to recompile electron from source.

**Comment by nshmyrev** [comment]
Alternatively you can simply install node.js 6.3.0 (version 49) which electron uses (https://github.com/electron/electron/releases/tag/v1.3.0)

**Comment by causztic** [comment]
I have a feeling it's homebrew screwing up my links again..

**Comment by causztic** [comment]
ok I just tried clearing everything (on homebrew) and it seems that it is really a problem on Electron's end. An error from the future
