### ISSUE TITLE
How I run on node v6.2.2 with npm 3.10.6?

### ISSUE THREAD

**Issue by bberaldi** [cmusphinx/node-pocketsphinx#33]
This is my error, I tried with sudo, -g, withou --save-dev and downloading the project, but without success.
Could you help me?

`_ npm install pocketsphinx --save-dev

> pocketsphinx@5.0.7 install /node_modules/pocketsphinx
> cmake-js compile

(node:5545) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:5545) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info REP Build has been failed, trying to do a full rebuild.
ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! Linux 4.6.0-040600-lowlatency
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx" "--save-dev"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.`

**Comment by nshmyrev** [comment]
You need to install requirements listed in README first, in particular, cmake.
