### ISSUE TITLE
Acoustic model and LM and dic

### ISSUE THREAD

**Issue by ahmedalbakiri** [cmusphinx/node-pocketsphinx#34]
Can I used it to recognition any language or just for English ?

**Comment by nshmyrev** [comment]
You can find models for other supported languages [in our downloads area](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/).

**Comment by ahmedalbakiri** [comment]
So, I have already build my acoustic model and LM and dic, and the sound is
in .wav.
can this work there?

2016-10-05 10:58 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
Yes

**Comment by ahmedalbakiri** [comment]
Thanks, for your fast response,
I have implemented it and I have got this results,
==============================================
_exports_Hypothesis { prob: -4802, bestScore: -5894, hypstr: '' }
INFO: ngram_search.c(1027): bestpath 0.00 CPU 0.000 xRT
INFO: ngram_search.c(1030): bestpath 0.00 wall 0.000 xRT
<s> 9 15
<sil> 16 192
<sil> 193 380
<sil> 381 440
</s> 441 590
================================================
 why text that recognize is empty? Is it because the text I work on is in
arabic or what?
thanks in advance.

2016-10-05 14:09 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
Please provide more complete data about your problem - what do you run exactly, what is exactly in the log output, what is your data file, what are your models, etc.

**Comment by ahmedalbakiri** [comment]
All you need it is in attachment.

2016-10-05 16:41 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
I'm sorry, I do not see any attachments. Maybe you can simply share the file with dropbox/google drive and give here a link.

**Comment by ahmedalbakiri** [comment]
The below is the link in google drive.

https://drive.google.com/open?id=0BxN0qMy1FI89cS03OWIyemFXUHM




2016-10-05 17:38 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by ahmedalbakiri** [comment]
Mr Nickolay, did you found where is the problem, I try to solve it, but I
still get the same output

<s> 9 15
<sil> 16 192
<sil> 193 380
<sil> 381 440
</s> 441 590

its give all the .wav is sil, where there is sound in that file, what is
going on?

I have search no solution is found? where is the problem?

2016-10-05 17:59 GMT+03:00 ahmed Parakletos <ahmedalbakiri@gmail.com>:

**Comment by nshmyrev** [comment]
I checked your files. I do not think your model is properly trained. For example, your dictionary doesn't follow tutorial recommendation to use phones or word-specific phones. Your phones are whole syllables which is not a good idea. I also not not know how much training data do you have, what is the error rate during training and so on.

I recommend you to fix model training first and share the model training folder if you still have problems.

**Comment by ahmedalbakiri** [comment]
I train using context independent (ci), the WER and the results I have in
this link,


https://drive.google.com/open?id=0BxN0qMy1FI89UHVmVHd2RlBhZTA

2016-10-09 19:21 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
You need to use proper phoneset first. Then you need to share a whole model training folder.

**Comment by ahmedalbakiri** [comment]
The whole model is in link, and the results I have is good with these .dic
file as you see in results file.

https://drive.google.com/open?id=0BxN0qMy1FI89UHVmVHd2RlBhZTA

2016-10-09 20:30 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
You do not have required amount of data for training too. As I said, follow the tutorial recommendations in order to get a working system.

**Comment by ahmedalbakiri** [comment]
do you mean increase the number of sound, to train different  speakers?

2016-10-09 20:54 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
http://cmusphinx.sourceforge.net/wiki/tutorialam

> - 1 hour of recording for command and control for single speaker
> - 5 hour of recordings of 200 speakers for command and control for many speakers
> - 10 hours of recordings for single speaker dictation
> - 50 hours of recordings of 200 speakers for many speakers dictation

**Comment by ahmedalbakiri** [comment]
Thanks, I now modify the dict and got a results, but its not good results,
it is recognition is bad

_exports_Hypothesis { prob: 0, bestScore: -22760, hypstr: 'لَمْ' }
INFO: ngram_search.c(1027): bestpath 0.00 CPU 0.000 xRT
INFO: ngram_search.c(1030): bestpath 0.00 wall 0.000 xRT
<s> 9 13
لَمْ 14 590
لَمْ

why its in previous previous dic produce a good results in the results
folder based WER, but in the pocketsphinx node give a SIL, and now after
modification to dic file give results, its not that good, but there is some
output?



2016-10-09 21:14 GMT+03:00 Nickolay V. Shmyrev <notifications@github.com>:

**Comment by nshmyrev** [comment]
> why its in previous previous dic produce a good results in the results
folder based WER, but in the pocketsphinx node give a SIL, and now after
modification to dic file give results, its not that good, but there is some
output?

When you do not have enough data results are unstable.
