### ISSUE TITLE
Methods

### ISSUE THREAD

**Issue by reejinbouk** [cmusphinx/node-pocketsphinx#35]
Hello
Which methods does supported by this library?
only Decoder or anything else? where can I get this info?
And how can I use JSGF rules?
thank you

**Comment by nshmyrev** [comment]
> only Decoder or anything else? where can I get this info?

You can check swig files:

https://github.com/cmusphinx/sphinxbase/tree/master/swig

and

https://github.com/cmusphinx/pocketsphinx/tree/master/swig

> And how can I use JSGF rules?

I'm sorry, what exactly do you want to do? Not many of JSGF functions are present in bindings.
