### ISSUE TITLE
Checking for module 'sphinxbase>=5prealpha'

### ISSUE THREAD

**Issue by TheMagicInventor** [cmusphinx/node-pocketsphinx#36]
yes, I installed all the dependencies...

-- Checking for module 'sphinxbase>=5prealpha'
--   
CMake Error at /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.6/Modules/FindPkgConfig.cmake:597 (_pkg_check_modules_internal)
  CMakeLists.txt:6 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/magicinventor/.nvm/versions/node/v6.8.0/lib/node_modules/pocketsphinx/build/CMakeFiles/CMakeOutput.log".

**Comment by nshmyrev** [comment]
You need to configure PKG_CONFIG_PATH and ensure pkg-config knows about pocketsphinx.
