### ISSUE TITLE
Error while installing Pocketsphinx in nodejs

### ISSUE THREAD

**Issue by kate008** [cmusphinx/node-pocketsphinx#38]
I try to use the Pocketsphinx in my nodejs project while installing this I am getting this error

pm ERR! Linux 3.16.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v4.5.0
npm ERR! npm v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: cmake-js compile
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR! npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

Please,help me to solve this error.

Thanks in advance.

**Comment by nshmyrev** [comment]
Please provide complete output, not just the last lines.

**Comment by kate008** [comment]
This is the log,I try to install the "npm install pocketsphinx" and it throwing like this:


npm WARN package.json cmake-js@3.3.1 No bin file found at ./bin/cmake-js
|
> pocketsphinx@5.0.7 install /home/apptivo/cappius/Munwar/test_lda_topic_mining/node_modules/pocketsphinx
> cmake-js compile

info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info REP Build has been failed, trying to do a full rebuild.
ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm ERR! Linux 3.16.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pocketsphinx"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! This is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/apptivo/cappius/Munwar/test_lda_topic_mining/npm-debug.log

**Comment by nshmyrev** [comment]
It says you need to install cmake.

**Comment by kate008** [comment]
yes I installed that also as "npm install cmake.js",still throwing the error.

As I am new to this ,I am not sure whether I am following the correct procedure.

Please help on this.

**Comment by nshmyrev** [comment]
No, cmake and cmake-js are separate packages. You need to install cmake first. If you are on Ubuntu run `sudo apt-get install cmake`.

Visit http://cmake.org/ or use your distribution package manager like apt-get or yum.

**Comment by kate008** [comment]
Now it is showing like this 

**CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.1 or higher is required.  You are running version 2.8.12.2**

**Comment by nshmyrev** [comment]
The messages are self-explaining
