### ISSUE TITLE
npm install fails with "no matching function for call to 'ngram_model_write'" and "no known conversion from 'int' to 'ngram_file_type_t'"

### ISSUE THREAD

**Issue by hagitarowe** [cmusphinx/node-pocketsphinx#39]
Node: 6.2.1
CMake: 3.7.2
CMake-js: 3.4.0
Sphinxbase: 5prealalpha
Pocketsphinx: 5prealalpha
Swig: 3.0.11
PkgConfig: 0.29.1

As mentioned in the title, npm install fails with the error:

/Users/george.rowe/Desktop/Sandbox/node/node-pocketsphinx/build/sphinxbase/sb.cpp:1934:20: error: 
      no matching function for call to 'ngram_model_write'
        *errcode = ngram_model_write(self, path, ftype);
                   ^~~~~~~~~~~~~~~~~
/usr/local/include/sphinxbase/ngram_model.h:116:5: note: candidate function not
      viable: no known conversion from 'int' to 'ngram_file_type_t'
      (aka 'ngram_file_type_e') for 3rd argument
int ngram_model_write(ngram_model_t *model, const char *file_name,

Full log.txt attached.

[log.txt](https://github.com/cmusphinx/node-pocketsphinx/files/734276/log.txt)

**Comment by nshmyrev** [comment]
Fixed now. Please update pocketsphinx and sphinxbase and try again.

**Comment by hagitarowe** [comment]
[100%] Built target PocketSphinx

Confirmed, thank you for the quick response!
