### ISSUE TITLE
Assertion `val->IsUint8Array()' failed.

### ISSUE THREAD

**Issue by dennisblokland** [cmusphinx/node-pocketsphinx#40]
`/usr/bin/nodejs[2396]: ../src/node_buffer.cc:197:char* node::Buffer::Data(v8::Local<v8::Value>): Assertion `val->IsUint8Array()' failed.
 1: node::Abort() [node]
 2: node::Assert(char const* const (*) [4]) [node]
 3: 0x556e0f2d54ac [node]
 4: 0x7fee85c94ed3 [/home/dennis/discord-bot/node_modules/pocketsphinx/build/Release/PocketSphinx.node]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 6: 0x556e0eba094e [node]
 7: 0x556e0eba11df [node]
 8: 0x256f353092a7
Aborted (core dumped)`

i get this error. while using this peace of code:

`                var readable = receiver.createPCMStream(user)

                decoder.startUtt();
                decoder.processRaw(readable, false, false);
                decoder.endUtt();
                console.log(decoder.hyp())`

the createPCMStream returns a readable stream.

im running node v6.9.5

**Comment by nshmyrev** [comment]
Try with node 5.2

**Comment by nshmyrev** [comment]
Also it seems you are using some API for getting PCM data (that createPCMStream). You need to point which exactly API you are using.

**Comment by dennisblokland** [comment]
sorry forgot about that.. its [discord.js](https://discord.js.org) and this is the [function](https://discord.js.org/#/docs/main/stable/class/VoiceReceiver?scrollTo=createPCMStream)

**Comment by dennisblokland** [comment]
and i cant install the older version im on ubuntu 16.10

**Comment by nshmyrev** [comment]
Ok, you need to get buffer of data to pass it to decoder, you are trying to pass the stream object instead. You should read data from the stream and pass to the decoder in a loop manually.
