### ISSUE TITLE
ERR! OMG ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by Code42Cate** [cmusphinx/node-pocketsphinx#44]
#
Hey, hope you can help me!
I tried:
~$ sudo npm install -g pocketsphinx
but i get the error:
ERR! OMG ENOENT: no such file or directory, uv_chdir
full error log here:
[log.txt](https://github.com/cmusphinx/node-pocketsphinx/files/1143046/log.txt)
and my terminal output:
[console.txt](https://github.com/cmusphinx/node-pocketsphinx/files/1143054/console.txt)

**Comment by nshmyrev** [comment]
We are not yet compatible with node8, see for details

https://github.com/cmusphinx/node-pocketsphinx/issues/37
