### ISSUE TITLE
NPM install fail using nodejs 8.0

### ISSUE THREAD

**Issue by TuxSeb** [cmusphinx/node-pocketsphinx#45]
Hello, i have an issue when i try to use npm install 

I installed pocketsphinx and sphinxbase from the website, both 5.0.7

logs: https://gist.github.com/TuxSeb/445a224cd3cbd678d28f03e9b699c57f

PKG_CONFIG_PATH is set to /usr/local/lib/pkgconfig

node.js version:  8.0.0
npm version: 5.3.0
swig version: 3.0.8
cmake version: 3.5.1

Thanks !

**Comment by nshmyrev** [comment]
Duplicate of https://github.com/cmusphinx/node-pocketsphinx/issues/37
