### ISSUE TITLE
install  error

### ISSUE THREAD

**Issue by Messilimeng** [cmusphinx/node-pocketsphinx#48]
![image](https://user-images.githubusercontent.com/12272166/28619299-3cacf1a8-723a-11e7-8a5a-d4c7afea2111.png)

**Comment by Messilimeng** [comment]
info TOOL Using Unix Makefiles generator.
info TOOL Using c++11 compiler standard.
info REP Build has been failed, trying to do a full rebuild.
ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN thinkjs-application@1.0.0 No repository field.
npm ERR! Linux 3.10.0-327.22.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "pocketsphinx"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script 'cmake-js compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pocketsphinx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cmake-js compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pocketsphinx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pocketsphinx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ships/npm-debug.log
[root@iZbp19qnmldt4kzl6t8seyZ ships]#

**Comment by nshmyrev** [comment]
Simply read the error message, it tells you what to do.
