### ISSUE TITLE
ERROR: "ngram_search.c", line 1139: Couldn't find <s> in first frame

### ISSUE THREAD

**Issue by Messilimeng** [cmusphinx/node-pocketsphinx#51]
![image](https://user-images.githubusercontent.com/12272166/28968721-0191e97c-7954-11e7-9e6f-39018be67997.png)

**Comment by morsedev** [comment]
@Messilimeng I have the same error, did you resolve it?

**Comment by Messilimeng** [comment]
@morsedev  no

**Comment by nshmyrev** [comment]
No way to reproduce the error
