### ISSUE TITLE
error: ‘class v8::Object’ has no member named ‘GetHiddenValue’

### ISSUE THREAD

**Issue by hczhcz** [cmusphinx/node-pocketsphinx#53]
`npm install pocketsphinx` failed probably because of V8's API changes.

* Node.js version: 8.9.4
* OS: Linux Mint 18.2
* Error message: `.../node_modules/pocketsphinx/build/sphinxbase/sb.cpp:5253:49: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’`

For reference: https://github.com/node-inspector/v8-profiler/pull/96/files

**Comment by nshmyrev** [comment]
Duplicate of https://github.com/cmusphinx/node-pocketsphinx/issues/37
