### ISSUE TITLE
build/sphinxbase/sb.cpp missing

### ISSUE THREAD

**Issue by highvoltage379** [cmusphinx/node-pocketsphinx#54]
Hi

I'm trying to run npm install but I get this error:

```
Scanning dependencies of target SphinxBase
[ 16%] Generating swig bindings
1.4.2
[ 33%] Building CXX object sphinxbase/CMakeFiles/SphinxBase.dir/sb.cpp.o
c++: error: /home/loophole/Documents/EventBots/speechRecognition/node-pocketsphinx/build/sphinxbase/sb.cpp: Aucun fichier ou dossier de ce type
c++: fatal error: no input files
compilation terminated.
sphinxbase/CMakeFiles/SphinxBase.dir/build.make:66 : la recette pour la cible « sphinxbase/CMakeFiles/SphinxBase.dir/sb.cpp.o » a échouée
make[2]: *** [sphinxbase/CMakeFiles/SphinxBase.dir/sb.cpp.o] Erreur 1
CMakeFiles/Makefile2:85 : la recette pour la cible « sphinxbase/CMakeFiles/SphinxBase.dir/all » a échouée
make[1]: *** [sphinxbase/CMakeFiles/SphinxBase.dir/all] Erreur 2
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
ERR! OMG Process terminated: 2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pocketsphinx@5.0.7 install: `cmake-js compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pocketsphinx@5.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Okay, some parts are in french but I guess you get the main idea: cmake can't find build/sphinxbase/sb.cpp and thus can't make sphinxbase/CMakeFiles/SphinxBase.dir/sb.cpp.o.

Full log:  [2018-02-16T14_44_21_824Z-debug.log](https://github.com/cmusphinx/node-pocketsphinx/files/1731786/2018-02-16T14_44_21_824Z-debug.log)

I'm using:
npm@5.5.1
node@8.9.1
swig@1.4.2 (if i do "swig -v", but the script says "Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.8", minimum required is "3.0.7") ")

Maybe I have a problem with swig ?

I would like to add that I may have some version conflicts regarding sphinxbase and pocketsphinx. Indeed, I installed those packages in three different ways : sudo apt-get install (bad idea, since you get old version. I removed those packages), along with ROS and from github.
ROS installations is now cleared I think.

Thank you.

**Comment by nshmyrev** [comment]
> swig@1.4.2 (if i do "swig -v", but the script says "Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.8", minimum required is "3.0.7") ")

try to solve this problem first. `swig -version` should print a proper version. Swig does not support -v option.

Node 8.9 is also not supported.
